name: Call API on Push

on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  call-api:
    runs-on: ubuntu-latest
    steps:
      - name: Make API Request to Huawei Cloud Pipeline
        run: |
          curl -X POST \
            -H "Content-Type: application/json" \
            -d '{}' \
            "${{ secrets.CODEARTS_WEBHOOK_URL }}"

